<a href="https://colab.research.google.com/github/worldofaryavart/colab_notebooks/blob/colabnotebook/Customization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.math.add(1,2))
print(tf.math.add([1,2],[3,4]))
print(tf.math.square(5))
print(tf.math.reduce_sum([1,2,3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
print(tf.math.square(3) + tf.math.square(3))

tf.Tensor(18, shape=(), dtype=int32)


In [ ]:
x = tf.linalg.matmul([[1]],[[2,3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [ ]:
print(x.shape)

(1, 2)


In [ ]:
import numpy as np
ndarray = np.ones([3,3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.math.multiply(ndarray, 42)
print(tensor)

print(np.add(tensor,1))
print(" ")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
 
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [ ]:
x = tf.random.uniform([3,3])

print("Is there a GPU available: ")
print(tf.config.list_physical_devices("GPU"))
print("IS the Tnsor on GPU #0: "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
IS the Tnsor on GPU #0: 
True


In [ ]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.linalg.matmul(x, x)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 270.10ms
On GPU:
10 loops: 0.94ms


In [ ]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write(""" Line 1
Line 2
Line 3
""")

ds_file = tf.data.TextLineDataset(filename)
ds_file

<TextLineDatasetV2 element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [ ]:
ds_tensors = ds_tensors.map(tf.math.square).shuffle(2).batch(2)
ds_file =ds_file.batch(2
                       )

In [ ]:
print("Elements of ds_tensors:")
for x in ds_tensors:
  print(x)

print('\nElements in ds_file')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor(
[[  16   81]
 [ 625 1296]], shape=(2, 2), dtype=int32)
tf.Tensor([[256   1]], shape=(1, 2), dtype=int32)

Elements in ds_file
tf.Tensor([b' Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3'], shape=(1,), dtype=string)


# Custom Layers


In [ ]:
import tensorflow as tf


In [ ]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10, input_shape = (None, 5))

In [ ]:
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.35406154,  0.09979361, -0.20109692,  0.0530178 , -0.04595423,
         -0.57412034,  0.17480356, -0.2457934 ,  0.31882966, -0.02894747],
        [ 0.20609665, -0.38175154,  0.12585121, -0.30997077,  0.5313062 ,
         -0.22685066, -0.2716477 ,  0.18424624,  0.36317098, -0.44100082],
        [-0.26811472, -0.40152574,  0.0050953 ,  0.59212595, -0.46947962,
          0.34474063, -0.33980393, -0.2765954 ,  0.06437731,  0.03672153],
        [ 0.29378808, -0.3960079 ,  0.02177531,  0.4742853 ,  0.31428486,
          0.29790282,  0.29767138,  0.08527744,  0.36201006,  0.42728573],
        [-0.18715209, -0.6177513 , -0.29402676,  0.49829656, -0.53848296,
         -0.08091635,  0.32414824, -0.60431737,  0.08044118, -0.34890753]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [ ]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.35406154,  0.09979361, -0.20109692,  0.0530178 , -0.04595423,
         -0.57412034,  0.17480356, -0.2457934 ,  0.31882966, -0.02894747],
        [ 0.20609665, -0.38175154,  0.12585121, -0.30997077,  0.5313062 ,
         -0.22685066, -0.2716477 ,  0.18424624,  0.36317098, -0.44100082],
        [-0.26811472, -0.40152574,  0.0050953 ,  0.59212595, -0.46947962,
          0.34474063, -0.33980393, -0.2765954 ,  0.06437731,  0.03672153],
        [ 0.29378808, -0.3960079 ,  0.02177531,  0.4742853 ,  0.31428486,
          0.29790282,  0.29767138,  0.08527744,  0.36201006,  0.42728573],
        [-0.18715209, -0.6177513 , -0.29402676,  0.49829656, -0.53848296,
         -0.08091635,  0.32414824, -0.60431737,  0.08044118, -0.34890753]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [ ]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                 shape= [int(input_shape[-1]),
                                         self.num_outputs])
  def call(self, inputs):
    return tf.matmul(inputs, self.kernel)
layer = MyDenseLayer(10)

In [ ]:
_ = layer(tf.zeros([10,5]))

In [ ]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_1/kernel:0']


In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name = '')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2,kernel_size, padding = 'same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training = False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training = training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training = training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training = training)

    x +=input_tensor
    return tf.nn.relu(x)

block = ResnetIdentityBlock(1, [1,2,3])

In [ ]:
_ = block(tf.zeros([1,2,3,3]))



In [ ]:
block.layers

In [ ]:
len(block.variables)

18

In [ ]:
block.summary()

Model: ""
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             multiple                  4         
                                                                 
 batch_normalization (Batch  multiple                  4         
 Normalization)                                                  
                                                                 
 conv2d_1 (Conv2D)           multiple                  4         
                                                                 
 batch_normalization_1 (Bat  multiple                  8         
 chNormalization)                                                
                                                                 
 conv2d_2 (Conv2D)           multiple                  9         
                                                                 
 batch_normalization_2 (Bat  multiple                  12        


In [ ]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
my_seq.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, None, None, 1)     4         
                                                                 
 batch_normalization_3 (Bat  (None, None, None, 1)     4         
 chNormalization)                                                
                                                                 
 conv2d_4 (Conv2D)           (None, None, None, 2)     4         
                                                                 
 batch_normalization_4 (Bat  (None, None, None, 2)     8         
 chNormalization)                                                
                                                                 
 conv2d_5 (Conv2D)           (None, None, None, 3)     9         
                                                                 
 batch_normalization_5 (Bat  (None, None, None, 3)     1