<a href="https://colab.research.google.com/github/worldofaryavart/colab_notebooks/blob/colabnotebook/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics and Fundamentels of pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


# Introduction to Tensors
Creating Tensors


In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][0][0]

tensor(1)

##Random tensors



In [ ]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3443, 0.1091, 0.9696, 0.3271],
        [0.2607, 0.9985, 0.6234, 0.7771],
        [0.7365, 0.6398, 0.7399, 0.2305]])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor.shape

torch.Size([3, 4])

###Zeros and Ones

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.ones_like(input = zeros)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 10,2)

tensor([0, 2, 4, 6, 8])

###Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype = torch.float64,
                            device = None,
                            requires_grad = False)

In [ ]:
float_32_tensor.dtype

torch.float64

###Manipulating tensors





In [ ]:
# create a tensor and add
tensor = torch.tensor([1, 2,3])
tensor = tensor + 10

In [ ]:
# multiply
tensor * 10


tensor([110, 120, 130])

In [ ]:
# subtract
tensor - 10

tensor([1, 2, 3])

In [ ]:
# pytorch in-built functions
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [ ]:
torch.add(tensor, 10)

tensor([21, 22, 23])

In [ ]:
torch.sub(tensor, 10)

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication
%%time
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
torch.matmul(tensor1, tensor2)

CPU times: user 861 µs, sys: 0 ns, total: 861 µs
Wall time: 9.35 ms


tensor(32)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor1[i] * tensor2[i]
value

CPU times: user 2.11 ms, sys: 0 ns, total: 2.11 ms
Wall time: 6.6 ms


tensor(32)

In [ ]:
tensor_A = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])
tensor_B = torch.tensor([[7,10],
                     [8,11],
                     [9,12]])
print(f"tensor_A: {tensor_A.shape}")
print(f"tensor_B: {tensor_B.shape}")
# tensor_B = torch.transpose(tensor_B, 0, 1)
tensor_B = tensor_B.T
print(f"tensor_B: {tensor_B.shape}")
tensor_C = torch.mm(tensor_A, tensor_B)
tensor_C.shape

tensor_A: torch.Size([3, 2])
tensor_B: torch.Size([3, 2])
tensor_B: torch.Size([2, 3])


torch.Size([3, 3])

In [ ]:
#  Finding the min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()
x.dtype

torch.int64

In [ ]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Find the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping , stacking, squeezing and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1., 10. )
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z = x.view(1, 9)
z, z.shape, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x = torch.rand(2, 4, 5)
x.size()

torch.Size([2, 4, 5])

In [ ]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 4])

###Indexing (selecting data from tensors)

In [ ]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket ( dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket ( lat dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[:, 2, 2]

tensor([9])

In [ ]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
#Tensor to Nu mpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Reproducibility
torch.rand(3,3)