<a href="https://colab.research.google.com/github/worldofaryavart/colab_notebooks/blob/colabnotebook/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics and Fundamentels of pytorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


# Introduction to Tensors
Creating Tensors


In [3]:
# scaler
scaler = torch.tensor(7)
scaler

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [44]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [45]:
TENSOR.ndim

3

In [46]:
TENSOR.shape

torch.Size([1, 3, 3])

In [40]:
TENSOR[0][0][0]

tensor(1)

##Random tensors



In [50]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9965, 0.3186, 0.8697, 0.1621],
        [0.2297, 0.8777, 0.8984, 0.9386],
        [0.0952, 0.3708, 0.2194, 0.2490]])

In [54]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [53]:
random_tensor.shape

torch.Size([3, 4])

###Zeros and Ones

In [55]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [58]:
torch.ones_like(input = zeros)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [61]:
torch.arange(0, 10,2)

tensor([0, 2, 4, 6, 8])

###Tensor Datatypes

In [65]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype = torch.float64,
                            device = None,
                            requires_grad = False)

In [66]:
float_32_tensor.dtype

torch.float64