<a href="https://colab.research.google.com/github/worldofaryavart/colab_notebooks/blob/colabnotebook/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics and Fundamentels of pytorch


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


# Introduction to Tensors
Creating Tensors


In [2]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0][0][0]

tensor(1)

##Random tensors



In [15]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4646, 0.1260, 0.7369, 0.7939],
        [0.0151, 0.3591, 0.2242, 0.7551],
        [0.9724, 0.3410, 0.3427, 0.1224]])

In [16]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
random_tensor.shape

torch.Size([3, 4])

###Zeros and Ones

In [18]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
torch.ones_like(input = zeros)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [22]:
torch.arange(0, 10,2)

tensor([0, 2, 4, 6, 8])

###Tensor Datatypes

In [23]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype = torch.float64,
                            device = None,
                            requires_grad = False)

In [24]:
float_32_tensor.dtype

torch.float64

###Manipulating tensors





In [25]:
# create a tensor and add
tensor = torch.tensor([1, 2,3])
tensor = tensor + 10

In [26]:
# multiply
tensor * 10


tensor([110, 120, 130])

In [27]:
# subtract
tensor - 10

tensor([1, 2, 3])

In [28]:
# pytorch in-built functions
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [29]:
torch.add(tensor, 10)

tensor([21, 22, 23])

In [30]:
torch.sub(tensor, 10)

tensor([1, 2, 3])

In [31]:
# Matrix multiplication
%%time
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
torch.matmul(tensor1, tensor2)

CPU times: user 900 µs, sys: 164 µs, total: 1.06 ms
Wall time: 25.2 ms


tensor(32)

In [32]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor1[i] * tensor2[i]
value

CPU times: user 1.56 ms, sys: 0 ns, total: 1.56 ms
Wall time: 3.99 ms


tensor(32)

In [33]:
tensor_A = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])
tensor_B = torch.tensor([[7,10],
                     [8,11],
                     [9,12]])
print(f"tensor_A: {tensor_A.shape}")
print(f"tensor_B: {tensor_B.shape}")
# tensor_B = torch.transpose(tensor_B, 0, 1)
tensor_B = tensor_B.T
print(f"tensor_B: {tensor_B.shape}")
tensor_C = torch.mm(tensor_A, tensor_B)
tensor_C.shape

tensor_A: torch.Size([3, 2])
tensor_B: torch.Size([3, 2])
tensor_B: torch.Size([2, 3])


torch.Size([3, 3])

In [34]:
#  Finding the min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
# Find the max
torch.max(x), x.max()
x.dtype

torch.int64

In [37]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Find the positional min and max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.argmin()

tensor(0)

In [41]:
x[0]

tensor(0)

In [42]:
x.argmax()

tensor(9)

In [43]:
x[9]

tensor(90)

### Reshaping , stacking, squeezing and unsqueezing tensors

In [45]:
import torch
x = torch.arange(1., 10. )
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [50]:
z = x.view(1, 9)
z, z.shape, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [51]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
x = torch.rand(2, 4, 5)
x.size()

torch.Size([2, 4, 5])

In [56]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 4])

###Indexing (selecting data from tensors)

In [57]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# Let's index on the middle bracket ( dim = 1)
x[0][0]

tensor([1, 2, 3])

In [60]:
# Lets index on the most inner bracket ( lat dimension)
x[0][0][0]

tensor(1)